#!/bin/bash
FROM_PATH=$1
TO_PATH=$2
MODULE_NAME=$3
PROJECT_APPS=${*:4}
JSREFACTOR_DIR="$(dirname "$(readlink -f "$0")")"
TRANSFORMER_PATH="$JSREFACTOR_DIR/move-file.js"

jscodeshift -t "$TRANSFORMER_PATH" ./ --fromPath="$FROM_PATH" --toPath="$TO_PATH" --currentModuleName="$MODULE_NAME" --parser=flow &&
jscodeshift -t "$TRANSFORMER_PATH" $PROJECT_APPS --moduleName="$MODULE_NAME" --fromPath="$FROM_PATH" --toPath="$TO_PATH" --parser=flow
echo "git mv $FROM_PATH $TO_PATH"
